//Form-Builder
export const ATTRIBUTE_RENDERER='rendererProductProperty';
export const ATTRIBUTE_RENDERER_CONTACT='CONTACT';
export const ATTRIBUTE_RENDERER_COMPANY='COMPANY'
export const ATTRIBUTE_RENDERER_TEXTAREA='TEXTAREA';
export const ATTRIBUTE_RENDERER_READONLY='READONLY';
export const ATTRIBUTE_RENDERER_BSAPRODUCT='BSAPRODUCT';
export const ATTRIBUTE_PROPERTY_ISCONFIGSTORE='attributeIsConfigStore';
export const ATTRIBUTE_PROPERTY_REQUIRED_FOR_TRANSITION='attributeRequiredForTransition';
export const SERVICE_PROPERTY_REQUIRED_CONTACT_ROLES_FOR_OFFER='contactRolesRequiredForOffer';
export const SERVICE_PROPERTY_REQUIRED_CONTACT_ROLES_FOR_CONSTRUCTION='contactRolesRequiredForOffer';
export const TAXONOMY_PREFIX_CONTACT_ROLES='/contactRoles/';
